// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using efcore_issue;

namespace efcore_issue.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221018114016_MG_01")]
    partial class MG_01
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("efcore_issue.Root", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AnyProp")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roots");
                });

            modelBuilder.Entity("efcore_issue.Root", b =>
                {
                    b.OwnsOne("efcore_issue.Child1", "Child1", b1 =>
                        {
                            b1.Property<int>("RootId")
                                .HasColumnType("int");

                            b1.Property<string>("AnyProp")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.HasKey("RootId");

                            b1.ToTable("child1s");

                            b1.WithOwner()
                                .HasForeignKey("RootId");
                        });

                    b.OwnsOne("efcore_issue.Child2", "Child2", b1 =>
                        {
                            b1.Property<int>("RootId")
                                .HasColumnType("int");

                            b1.Property<string>("AnyProp")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.HasKey("RootId");

                            b1.ToTable("child2s");

                            b1.WithOwner()
                                .HasForeignKey("RootId");
                        });

                    b.OwnsMany("efcore_issue.Child3", "Child3", b1 =>
                        {
                            b1.Property<int>("RootId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("AnyProp")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RootId", "Id");

                            b1.ToTable("child3s");

                            b1.WithOwner()
                                .HasForeignKey("RootId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
